version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:v1.36.1-focal
    parallelism: 4
    working_directory: ~/app
    
    steps:
      - checkout
      - run: npm i -D @playwright/test
      - run: npx playwright install chrome
      - run:
          name: run the test.
          command: |
            TOTAL_SHARDS=4
            CURRENT_SHARD=${CIRCLE_NODE_INDEX}
            TEST_FILTER="*"
            if [ $CURRENT_SHARD -lt $TOTAL_SHARDS ]; then
              MODULO=$(( $CURRENT_SHARD % $TOTAL_SHARDS ))
              TEST_FILTER="test.spec.ts:${MODULO}"
            fi
            npx playwright test --project=chromium --reporter=line,allure-playwright || true
            # The build will fail if the tests fail, no need for "|| true"
            
      - run:
          name: downlaod allurectl
          command: |
            wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -O ./allurectl
            chmod +x ./allurectl
            ls -al allurectl

      - run:
          name: upload to testsops allure results
          # Add source command to execute code and make variables
          # available in current step.
          command: |
            export ALLURE_ENDPOINT=https://amielnoy.testops.cloud/
            export ALLURE_TOKEN=6dfe1319-dd1a-4794-9f07-986eb5406e92
            export ALLURE_PROJECT_ID=1
            export ALLURE_LAUNCH_NAME="playwright tests e2e"
            export ALLURE_LAUNCH_TAGS="release, critical"
            # Run upload process somewhere
            ./allurectl upload ./allure-results 


workflows:
  build:
    jobs:
      - build