version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:v1.36.1-focal
    working_directory: ~/app
    environment:
      # Set the JAVA_HOME variable to the Java installation path in the Docker image
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    steps:
      - checkout

      - run:
          command: npm i -D @playwright/test

      - run:
          command: npx playwright install chromium

      - run:
          command: npx playwright test --project=chromium --reporter=line,allure-playwright || true

      - run:
          command: |
            mkdir -p ~/artifacts
            cp -r ./allure-report ~/artifacts/
      
      - run:
          name: Install Allure Commandline
          command: npm install -g allure-commandline      

      - run:
          command: |
            npx allure generate allure-report --clean
            npx allure report generate -c -o allure-results
            npx allure report open -o allure-results --port 8080 http://35.171.159.248

workflows:
  build:
    jobs:
      - build
