version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:v1.36.1-focal
    parallelism: 4
    working_directory: ~/app

    steps:
      - checkout
      - run: npm i -D @playwright/test
      - run: npx playwright install chrome
      - run:
          name: run the test.
          command: |
            set -x
            TOTAL_SHARDS=4
            CURRENT_SHARD=${CIRCLE_NODE_INDEX}
            TEST_FILES=$(npx playwright test --list --project=chromium | grep -Eo '.*\.spec\.ts')
            echo "TEST_FILES: $TEST_FILES"

            TEST_FILTER=""
            for FILE in $TEST_FILES; do
              FILE_NUMBER=$(echo $FILE | grep -Eo '[0-9]+' | tail -n 1)
              echo "FILE: $FILE, FILE_NUMBER: $FILE_NUMBER"
              if [ -n "$FILE_NUMBER" ]; then
                FILE_NUMBER=$((FILE_NUMBER % TOTAL_SHARDS))
                echo "FILE_NUMBER (mod): $FILE_NUMBER"
                if [ "$FILE_NUMBER" -eq "$CURRENT_SHARD" ]; then
                  if [ -z "$TEST_FILTER" ]; then
                    TEST_FILTER="$FILE"
                  else
                    TEST_FILTER="$TEST_FILTER,$FILE"
                  fi
                fi
              fi
            done
            echo "TEST_FILTER: $TEST_FILTER"
            npx playwright test --project=chromium --reporter=line,allure-playwright --test-match="$TEST_FILTER"
            set +x
                  # The build will fail if the tests fail

      - run:
          name: download allurectl
          command: |
            wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -O ./allurectl
            chmod +x ./allurectl
            ls -al allurectl

      - run:
          name: upload to testsops allure results
          command: |
            export ALLURE_ENDPOINT=https://amielnoy.testops.cloud/
            export ALLURE_TOKEN=6dfe1319-dd1a-4794-9f07-986eb5406e92
            export ALLURE_PROJECT_ID=1
            export ALLURE_LAUNCH_NAME="playwright tests e2e"
            export ALLURE_LAUNCH_TAGS="release, critical"
            # Run upload process somewhere
            ./allurectl upload ./allure-results

workflows:
  build:
    jobs:
      - build
